In [1]:
# Numpy

In [2]:
import numpy as np

In [3]:
# Tipe Data
# Numpy Array

# mirip list, tapi dia bisa handle data tipe numerik
# isinya data tipe numerik saja

# CRUD - create read update delete

In [6]:
# create
# np.array()

# contoh data 1 dimensi, dalam list/array langsung angka nya
nilai = [83,31,47,57,60]
print(nilai)

arr = np.array(nilai)
print(arr)
print(type(arr))

[83, 31, 47, 57, 60]
[83 31 47 57 60]
<class 'numpy.ndarray'>


In [10]:
nilai

[83, 31, 47, 57, 60]

In [7]:
arr

array([83, 31, 47, 57, 60])

In [11]:
# contoh data 2 dimensi, dalam list/array ada list/array lagi, baru isinya angka nya
nilai = [
    [83,31,47,57,60],
    [45,35,78,89,45],
    [56,78,89,45,21],
    ]

arr = np.array(nilai)

print(nilai)
print(arr)

[[83, 31, 47, 57, 60], [45, 35, 78, 89, 45], [56, 78, 89, 45, 21]]
[[83 31 47 57 60]
 [45 35 78 89 45]
 [56 78 89 45 21]]


In [12]:
# numpy array 2 dimensi isinya angka semua => matrix

In [19]:
# create
# selain np.array() yang bisa convert list isi angka ke bentuk numpy array
# ada juga cara lain untuk buat numpy array dari:
# isi nya angka 0 semua
arr = np.zeros(10)
print(arr)

# isi nya angka 1 semua
arr = np.ones(12)
print(arr)

# isi nya angka urut
arr = np.arange(20)
print(arr)

# isi nya angka random
arr = np.random.random(5)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.53782529 0.18070257 0.93667861 0.45673946 0.29752862]


In [21]:
# 0,1,2,3,... angka terakhir -1
arr = np.arange(20)
print(arr)

# 20,21,22,... angka terakhir -1
arr = np.arange(20, 50)
print(arr)

# 20, 55, 90, ... maksimal angka terakhir -1
arr = np.arange(20, 200, 35)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
[ 20  55  90 125 160 195]


In [23]:
# read
# shape sebuah numpy array

print(arr)
print(arr.shape)

[ 20  55  90 125 160 195]
(6,)


In [24]:
nilai = [
    [83,31,47,57,60],
    [45,35,78,89,45],
    [56,78,89,45,21],
    ]

arr = np.array(nilai)

print(arr)
print(arr.shape)

[[83 31 47 57 60]
 [45 35 78 89 45]
 [56 78 89 45 21]]
(3, 5)


In [25]:
# reshape mengubah bentuk

# balik ke create sebentar untuk menunjukkan cara membuat np array 2d dari teknik berikut
# isi nya angka 0 semua
arr = np.zeros((3, 5))
print(arr)

# isi nya angka 1 semua
arr = np.ones((3, 4))
print(arr)

# isi nya angka urut
arr = np.arange(20).reshape((2,10))
print(arr)

# isi nya angka random
arr = np.random.random(5).reshape((5,1))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[0.02970601]
 [0.34005753]
 [0.4085912 ]
 [0.71624415]
 [0.26297881]]


In [27]:
# read
# size sebuah numpy array
# total angka yang ada di sebuah numpy array, tidak peduli dimensinya
print(arr)
print(arr.shape)

[[0.02970601]
 [0.34005753]
 [0.4085912 ]
 [0.71624415]
 [0.26297881]]
(5, 1)


In [28]:

print(arr.size)

5


In [29]:
arr = np.arange(20).reshape((2,10))
print(arr)
print(arr.shape)
print(arr.size)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
(2, 10)
20


In [33]:
# cara buat numpy array dari: list, 0, 1, random, urut
# cara baca numpy array dari: shape, size

# update
# aritmatika + - * / ** %

# jualan kardus
panjang = [5, 10, 15]
lebar = [2, 30, 12]
tinggi = [5, 10, 5]

# volume kardusnya berapa?
arr_p = np.array(panjang)
arr_l = np.array(lebar)
arr_t = np.array(tinggi)

print(arr_p * arr_l * arr_t)


[  50 3000  900]


In [34]:
# coba membuat numpy array lalu lakukan teknik aritmatika
# aritmatik antara 2 numpy array, kedua numpy array tersebut bentuk (shape) harus sama

# broadcasting
# satu numpy array langsung aritmatik dengan angka
arr_p * 2

array([10, 20, 30])

In [35]:
panjang * 2

[5, 10, 15, 5, 10, 15]

In [42]:
arr_n = np.array(nilai)
edited_arr = (arr_n * 10 / 3 + 90 - 50) **2

In [44]:
# convert ke integer
(edited_arr / 10000).astype(int)

array([[10,  2,  3,  5,  5],
       [ 3,  2,  9, 11,  3],
       [ 5,  9, 11,  3,  1]])

In [45]:
arr_harga = np.array([10000,15000,20000])

# harga naik 15%

arr_harga =  arr_harga * 1.15
print(arr_harga)

[11500. 17250. 23000.]


In [49]:
# Matrix
# numpy array 2 dimensi
# isi angka semua
# jumlah data di setiap baris sama

arr_harga = np.array([
    [7500,8500,8000],
])

print(arr_harga)

[[7500 8500 8000]]


In [50]:
arr_penjualan = np.array([
    [12,10,9,20,50],
    [1,3,5,1,10],
    [32,54,12,70,100],
])
print(arr_penjualan)

[[ 12  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [51]:
# dot product
# 1 baris data matrix pertama dikalikan 1 kolom data matrix kedua

arr_harga.dot(arr_penjualan)

array([[ 354500,  532500,  206000,  718500, 1260000]])

In [52]:
# selain aritmatik, numpy array juga bisa merangkum data
# rata2 (mean)
# median
# total (sum)
# max, min
# std dev, dan angka2 statistik lainnya

# mean, sum, max, min
print(arr_penjualan)

[[ 12  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [53]:
# rata2 penjualan
print(arr_penjualan.mean())

25.933333333333334


In [56]:
#jumlah penjualan per hari
print(arr_penjualan.sum(axis=0))

# menambahkan item item di dimensi pertama, axis 0
# untuk numpy array 2 dimensi berarti kita jumlahkan baris 1 + baris 2 + baris 3 + ... sampai habis

[ 45  67  26  91 160]


In [ ]:
# [ 12  10   9  20  50] + [  1   3   5   1  10] + [ 32  54  12  70 100]

In [57]:
#jumlah penjualan per rasa
print(arr_penjualan.sum(axis=1))

# menambahkan item item di dimensi kedua, axis 1
# untuk numpy array 2 dimensi berarti kita jumlahkan kolom 1 + kolom 2 + kolom 3 + ... sampai habis

[101  20 268]


In [59]:
#max penjualan 1 hari per rasa
print(arr_penjualan.max(axis=1))

#min penjualan 1 hari per rasa
print(arr_penjualan.min(axis=1))

[ 50  10 100]
[ 9  1 12]


In [60]:
# indexing dan slicing
# mengambil 1 angka atau bbrp angka dari sebuah numpy array
print(arr_penjualan)

[[ 12  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [64]:
# berapa penjualan roti kaya di hari rabu?
print(arr_penjualan[2, 2])

12


In [61]:
# ambil data rasa coklat saja
arr_penjualan[0, :]

array([12, 10,  9, 20, 50])

In [62]:
# ambil data rasa coklat dan keju saja
arr_penjualan[0:2, :]

array([[12, 10,  9, 20, 50],
       [ 1,  3,  5,  1, 10]])

In [63]:
# ambil data rasa coklat dan keju saja
arr_penjualan[0:2, -1]

array([50, 10])

In [65]:
# cobain indexing dan slicing untuk numpy array 2 dimensi


In [66]:
# sort data di numpy array
print(arr_penjualan)

[[ 12  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [69]:
print(np.sort(arr_penjualan))

[[  1   1   3   5  10]
 [  9  10  12  20  50]
 [ 12  32  54  70 100]]


In [76]:
# shape dan reshape
arr_penjualan = np.array([
    [12,10,9,20,50],
    [1,3,5,1,10],
    [32,54,12,70,100],
])

print(arr_penjualan)

arr_penjualan.reshape((5,3))

[[ 12  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


array([[ 12,  10,   9],
       [ 20,  50,   1],
       [  3,   5,   1],
       [ 10,  32,  54],
       [ 12,  70, 100]])

In [77]:
arr_penjualan.reshape((15,))

array([ 12,  10,   9,  20,  50,   1,   3,   5,   1,  10,  32,  54,  12,
        70, 100])

In [78]:
arr_penjualan.reshape((1,15))

array([[ 12,  10,   9,  20,  50,   1,   3,   5,   1,  10,  32,  54,  12,
         70, 100]])

In [79]:
arr_penjualan.reshape((15,1))

array([[ 12],
       [ 10],
       [  9],
       [ 20],
       [ 50],
       [  1],
       [  3],
       [  5],
       [  1],
       [ 10],
       [ 32],
       [ 54],
       [ 12],
       [ 70],
       [100]])

In [74]:
# reshape menghilangkan hubungan antara baris dan kolom
# data penjualan kita aslinya baris pertama untuk rasa coklat
# kolom pertama untuk hari senin
# kalau di reshape, datanya bercampur

# misalnya mau tetap reshape bentuknya
# tapi yang tadinya teman sebaris jadi teman sekolom
# kita pakai transpose T

In [75]:
arr_penjualan.T

array([[ 12,   1,  32],
       [ 10,   3,  54],
       [  9,   5,  12],
       [ 20,   1,  70],
       [ 50,  10, 100]])

In [83]:
# query
# kondisi untuk meminta data tertentu

# misal untuk arr_penjualan
# minta yang data penjualan > 10 roti saja

kondisi = arr_penjualan > 10

lebih_10 = arr_penjualan[kondisi]
print(lebih_10)
len(lebih_10)

[ 12  20  50  32  54  12  70 100]


8

In [84]:
kondisi

array([[ True, False, False,  True,  True],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True]])

In [85]:
# teknik query
# bikin kondisi, dengan numpy array yang mau di cek
# kondisi ini akan menjadi index isi True dan False, jadi kita gunakan sebagai index untuk array kita
# hasilnya array 1 dimensi untuk data yang True saja

In [86]:
# khusus yang penjualan angka genap
arr_penjualan[arr_penjualan % 2 == 0]

array([ 12,  10,  20,  50,  10,  32,  54,  12,  70, 100])

In [91]:
# khusus yang < 50 dan > 10
arr_penjualan[(arr_penjualan < 50) & (arr_penjualan > 10)]

array([12, 20, 32, 12])

In [102]:
# khusus yang < 10 atau diatas 50
arr_penjualan[(arr_penjualan < 10) | (arr_penjualan > 50)]

array([100,   9,   1,   3,   5,   1,  54,  70, 100])

In [92]:
k1 = (arr_penjualan < 50)
k2 = (arr_penjualan > 10)

arr_penjualan[ k1 & k2 ]

array([12, 20, 32, 12])

In [93]:
copy = arr_penjualan

copy[0,0] = 100
print(copy)

[[100  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [94]:
print(arr_penjualan)

[[100  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [95]:
# dua nama untuk 1 data yang sama

# untuk bikin duplikat datanya, gunakan .copy()

copy = arr_penjualan.copy()

copy[0,0] = 0
print(copy)

[[  0  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [96]:
print(arr_penjualan)

[[100  10   9  20  50]
 [  1   3   5   1  10]
 [ 32  54  12  70 100]]


In [104]:
# buat dummy data untuk hasil lempar dua dadu enam sisi
dadu1 = (np.random.random(100) * 6 + 1).astype(int)
dadu2 = (np.random.random(100) * 6 + 1).astype(int)

hasil_dadu = dadu1 + dadu2
print(hasil_dadu)

[ 7  7  8 10  7  6 10  6  6  5 10 12  9 12  9  9  7  6  2  5  5  3  5  5
  6  9  7  5  9 12  8 11  7 11  5  4 11  8  9 10  3  9  6  7  7  4  6  3
  8  9  9  8  3  4  5  5  8  8  9 11 10  6  7  4  8  6  4  3  2 11  7  5
 10  9 10  8 10  4  5  7  6  8 10  5  6  5  8  4 11 11 10  5  7  3  9  9
  5 10 10  6]


In [105]:
# ada berapa kali hasil lempar dadunya lebih dari 10?
kondisi = hasil_dadu > 10
print(len(hasil_dadu[kondisi]))

# ada berapa kali hasil lempar dadunya lebih dari 7?
kondisi = hasil_dadu > 7
print(len(hasil_dadu[kondisi]))

# kumpulkan hasil lempar dadu yang ada di antara 1-6
kondisi1 = hasil_dadu >= 1
kondisi2 = hasil_dadu <= 6
print(hasil_dadu[kondisi1 & kondisi2])

# kumpulkan hasil lempar dadu yang nilainya 2 dan 12
kondisi1 = hasil_dadu == 2
kondisi2 = hasil_dadu == 12
print(hasil_dadu[kondisi1 | kondisi2])

10
46
[6 6 6 5 6 2 5 5 3 5 5 6 5 5 4 3 6 4 6 3 3 4 5 5 6 4 6 4 3 2 5 4 5 6 5 6 5
 4 5 3 5 6]
[12 12  2 12  2]


In [109]:
n = np.array([1,2,3])
n[n > 1]

array([2, 3])